apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astraea-artifacts-pvc
  namespace: astraea
  labels:
    app.kubernetes.io/name: astraea
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard