"use client";

import { useParams } from "next/navigation";
import { PraxisShell } from "@/components/praxis/PraxisShell";
import { ExecutiveReadout } from "@/components/praxis/ExecutiveReadout";
import { ValueCasePanel } from "@/components/praxis/ValueCasePanel";
import { ExpansionMap } from "@/components/praxis/ExpansionMap";
import Link from "next/link";
import { ArrowLeft, FileText, Printer } from "@phosphor-icons/react";

function resolvePackId(runId: string): string {
  if (runId.includes("erp") || runId.includes("onboarding") || runId.includes("identity")) return "identity-onboarding-drift";
  if (runId.includes("k8s") || runId.includes("ingress") || runId.includes("db") || runId.includes("database") || runId.includes("failover")) return "database-failover-lag";
  if (runId.includes("wan") || runId.includes("network") || runId.includes("isp") || runId.includes("starlink")) return "network-edge-failover";
  return "manufacturing-printer-gpo";
}

export default function ReadoutPrintPage() {
  const params = useParams();
  const runId = (params.runId as string) ?? "unknown";
  const packId = resolvePackId(runId);

  return (
    <PraxisShell>
      <div className="min-h-[100dvh] bg-[var(--praxis-bg)] text-[var(--praxis-bone)] print:bg-white print:text-black">
        <header className="border-b border-[var(--praxis-line)] bg-[var(--praxis-panel)] px-6 py-4 print:hidden">
          <div className="mx-auto flex max-w-7xl items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href={`/executive-readout/${runId}`} className="text-[var(--praxis-muted)] transition-transform duration-500 hover:scale-105 hover:text-[var(--praxis-bone)]">
                <ArrowLeft className="h-5 w-5" />
              </Link>
              <FileText className="h-6 w-6 text-[var(--praxis-mint)]" />
              <div>
                <h1 className="font-display text-xl font-medium">Executive Readout</h1>
                <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-[var(--praxis-muted)]">
                  Print-ready · {runId}
                </p>
              </div>
            </div>
            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 bg-[var(--praxis-bone)] px-4 py-2 font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--praxis-bg)] transition-transform duration-700 hover:scale-105"
            >
              <Printer className="h-3 w-3" /> Print
            </button>
          </div>
        </header>

        <main className="mx-auto max-w-4xl space-y-10 p-6 print:p-8 print:max-w-none">
          <section className="py-32 print:py-0 print:border-b print:border-gray-200 print:pb-8 print:mb-8">
            <div className="hidden print:block text-sm text-gray-500 mb-2">
              Praxis Proof Protocol v0.1 · {new Date().toISOString().split("T")[0]}
            </div>
            <ExecutiveReadout packId={packId} />
          </section>

          <section className="py-32 print:py-0 print:page-break-before">
            <h2 className="mb-4 font-display text-2xl font-medium print:text-xl print:text-black">Value Case</h2>
            <ValueCasePanel packId={packId} />
          </section>

          <section className="py-32 print:py-0 print:page-break-before">
            <h2 className="mb-4 font-display text-2xl font-medium print:text-xl print:text-black">Expansion Opportunities</h2>
            <ExpansionMap packId={packId} />
          </section>

          <footer className="hidden print:block border-t border-gray-200 pt-4 mt-8 text-xs text-gray-500">
            <p>Generated by Praxis — Proof-carrying field deployment for enterprise operations.</p>
            <p>Verify this proof: uvx praxis-verify artifacts/latest/{runId}/praxis_proof.json</p>
            <p>Repository: github.com/AngelP17/Praxis · Spec: docs/spec/praxis-proof-protocol.md</p>
          </footer>
        </main>
      </div>
    </PraxisShell>
  );
}
